spring.application.name=log-aggregator

spring.kafka.bootstrap-servers=localhost:9092

spring.datasource.url=jdbc:mysql://localhost:3306/log_aggregator
spring.datasource.username=appuser
spring.datasource.password=apppass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.kafka.producer.properties.allow.auto.create.topics=false

spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true

alert.window-ms=30000
alert.threshold=5